# Generated by Django 6.0.3 on 2026-04-05 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_project_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['deadline']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at']},
        ),
    ]
